// https://codeforces.com/problemset/problem/2234/A
/*
Problem: Euclid, Sequence and Two Numbers

Given a sequence generated by Euclid's algorithm, recover the two
starting numbers or report that the sequence is invalid.
*/

#include <bits/stdc++.h>
using namespace std;
#define ll long long
#define tata "\n"
#define vr(v, x) vector<ll> v(x)
#define rsort(a) sort(a.begin(), a.end(), greater<>())
#define loop(i, j, n) for (ll i = j; i < n; i++)
#define in(v) loop(i, 0, v.size()) cin >> v[i]

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    ll t;
    cin >> t;
    while (t--)
    {
        ll n, p = 1;
        cin >> n;
        vr(v, n);
        in(v);
        rsort(v);
        for (int i = 0; i < n - 2; i++)
        {
            if (v[i] % v[i + 1] != v[i + 2])
            {
                cout << -1 << tata;
                p = 0;
                break;
            }
        }
        if (p)
        {
            cout << v[0] << " " << v[1] << tata;
        }
    }
    return 0;
}
